import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Orbitron } from '@next/font/google'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const geistSans = localFont({
  src: "./fonts/MajorMonoDisplay-Regular.ttf",  // You can choose other subsets if needed
  weight: "400 700",  // Specify weights
})

const geistMono = localFont({
  src: "./fonts/MajorMonoDisplay-Regular.ttf",  // You can choose other subsets if needed
  weight: "400 700",  // Specify weights
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans} ${geistMono} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export const metadata: Metadata = {
  title: "UNGOLIANT",
  description: "A new microcosm in air-to-air dominance",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}